<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <AssemblyName>Lotus.SplashScreen</AssemblyName>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Lotus.SplashScreen</RootNamespace>
        <Nullable>enable</Nullable>

        <PublishAot>true</PublishAot>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <OptimizationPreference>Size</OptimizationPreference>
        <DebugType>None</DebugType>
        <DebugSymbols>false</DebugSymbols>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
        <PackageReference Include="Raylib-cs" Version="7.0.2" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="assets\**\*.png;assets\**\*.wav">
            <LogicalName>Assets/%(Filename)%(Extension)</LogicalName>
        </EmbeddedResource>
    </ItemGroup>
</Project>
